version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: geniusfinance-postgres
    ports:
      - "5433:5432"  # Map to port 5433 on host to avoid conflict
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: geniusfinance
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
